apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - www.techakademi.com
      - www.cloudtechakademi.com
    secretName: ssl-sertifika-staging
  rules:
  - host: www.techakademi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tech-wordpress-servisi
            port:
              number: 80
  - host: www.cloudtechakademi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cld-wordpress-servisi
            port:
              number: 80
